/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0df1b6d2ddb7e2b10e7f9437e28d48e3)
interface __BaseEnv_Env {
	ABUSE_METRICS: AnalyticsEngineDataset;
	SIGNAL_RATE_LIMIT: RateLimit;
	CONNECTION_RATE_LIMIT: RateLimit;
	ENVIRONMENT: "production";
	ROOMS: DurableObjectNamespace<import("./src/index").RendezvousRoom>;
	SIGNALS: DurableObjectNamespace<import("./src/index").SignalingRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RendezvousRoom" | "SignalingRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
