// Fails when worker-configuration.d.ts differs from what the lockfile-pinned
// Wrangler generates for wrangler.jsonc. It never rewrites the committed file.
// `wrangler types --check` only compares the header hash, so this regenerates
// into a sibling scratch file (keeping relative import paths identical) and
// compares the full output.
import { spawnSync } from 'node:child_process';
import { readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const committedName = 'worker-configuration.d.ts';
const scratchName = '.worker-configuration.check.d.ts';
const committedPath = join(root, committedName);
const scratchPath = join(root, scratchName);

// The header records the command line, which names the output path; the
// config hash that follows it is still compared.
function normalize(text) {
  return text.replace(
    /^(\/\/ Generated by Wrangler by running )`[^`]*`/m,
    '$1`wrangler types`',
  );
}

function firstDifference(expected, actual) {
  const expectedLines = expected.split('\n');
  const actualLines = actual.split('\n');
  const length = Math.max(expectedLines.length, actualLines.length);
  for (let index = 0; index < length; index += 1) {
    if (expectedLines[index] !== actualLines[index]) {
      return { line: index + 1, expected: expectedLines[index], actual: actualLines[index] };
    }
  }
  return null;
}

try {
  const result = spawnSync(
    'wrangler',
    ['types', '--include-runtime=false', scratchName],
    {
      cwd: root,
      encoding: 'utf8',
      env: { ...process.env, WRANGLER_SEND_METRICS: 'false' },
    },
  );
  if (result.error || result.status !== 0) {
    console.error(result.error?.message || result.stderr || result.stdout);
    console.error('Rendezvous type check failed: `wrangler types` did not run.');
    process.exitCode = 1;
  } else {
    let committed;
    try {
      committed = await readFile(committedPath, 'utf8');
    } catch {
      committed = '';
    }
    const generated = await readFile(scratchPath, 'utf8');
    const difference = firstDifference(normalize(generated), normalize(committed));
    if (difference) {
      console.error(
        `Rendezvous binding types are stale: ${committedName}:${difference.line}\n` +
          `  generated: ${difference.expected ?? '<end of file>'}\n` +
          `  committed: ${difference.actual ?? '<end of file>'}\n` +
          'Run `bun run --cwd workers/rendezvous types` and commit the result.',
      );
      process.exitCode = 1;
    } else {
      console.log(`Rendezvous binding types: ${committedName} is up to date.`);
    }
  }
} finally {
  await rm(scratchPath, { force: true });
}
